# Form implementation generated from reading ui file '.\ui_AboutTheProgram.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutTheProgram(object):
    def setupUi(self, AboutTheProgram):
        AboutTheProgram.setObjectName("AboutTheProgram")
        AboutTheProgram.resize(1625, 961)
        AboutTheProgram.setMinimumSize(QtCore.QSize(1280, 720))
        AboutTheProgram.setStyleSheet("*{\n"
"    color:white;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(AboutTheProgram)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(parent=AboutTheProgram)
        self.frame_12.setMaximumSize(QtCore.QSize(1280, 720))
        self.frame_12.setStyleSheet("*\n"
"{\n"
"    border: none;\n"
"     background-color:black;\n"
"    border-radius:30;\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.main_body = QtWidgets.QFrame(parent=self.frame_12)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(parent=self.main_body)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_frame.setObjectName("header_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header_frame)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.up_bar = QtWidgets.QFrame(parent=self.header_frame)
        self.up_bar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.up_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.up_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.up_bar.setObjectName("up_bar")
        self.pushButton = QtWidgets.QPushButton(parent=self.up_bar)
        self.pushButton.setGeometry(QtCore.QRect(1110, 30, 101, 41))
        self.pushButton.setStyleSheet("color: black;\n"
"background:white;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.up_bar)
        self.main_frame = QtWidgets.QFrame(parent=self.header_frame)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.main_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushFixMouse = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushFixMouse.setMinimumSize(QtCore.QSize(0, 500))
        self.pushFixMouse.setStyleSheet("color: black;\n"
"background:white;")
        self.pushFixMouse.setObjectName("pushFixMouse")
        self.horizontalLayout_3.addWidget(self.pushFixMouse)
        self.pushFixRegedit = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushFixRegedit.setMinimumSize(QtCore.QSize(0, 500))
        self.pushFixRegedit.setStyleSheet("color: black;\n"
"background:white;")
        self.pushFixRegedit.setObjectName("pushFixRegedit")
        self.horizontalLayout_3.addWidget(self.pushFixRegedit)
        self.pushFixInternet = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushFixInternet.setMinimumSize(QtCore.QSize(0, 500))
        self.pushFixInternet.setStyleSheet("color: black;\n"
"background:white;")
        self.pushFixInternet.setObjectName("pushFixInternet")
        self.horizontalLayout_3.addWidget(self.pushFixInternet)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=self.main_frame)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 601, 451))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.header_frame)
        self.horizontalLayout_11.addWidget(self.main_body)
        self.horizontalLayout.addWidget(self.frame_12)

        self.retranslateUi(AboutTheProgram)
        QtCore.QMetaObject.connectSlotsByName(AboutTheProgram)

    def retranslateUi(self, AboutTheProgram):
        _translate = QtCore.QCoreApplication.translate
        AboutTheProgram.setWindowTitle(_translate("AboutTheProgram", "Form"))
        self.pushButton.setText(_translate("AboutTheProgram", "Close"))
        self.pushFixMouse.setText(_translate("AboutTheProgram", "FixMouse"))
        self.pushFixRegedit.setText(_translate("AboutTheProgram", "FixRegedit"))
        self.pushFixInternet.setText(_translate("AboutTheProgram", "FixInternet"))
        self.textEdit.setHtml(_translate("AboutTheProgram", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">    Эта программа предназначена для устранения инпутлага, который может возникать при использовании компьютера. Инпутлаг — это задержка между вводом данных пользователем и реакцией системы на этот ввод. Программа включает в себя следующие функции:Фиксация проблем с мышью: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">1 Оптимизация настроек мыши для уменьшения задержки.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">2 Настройка реестра: Изменение параметров реестра для улучшения производительности системы.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">3 Фиксация интернет-соединения: Оптимизация настроек сети для уменьшения задержки при передаче данных.</span></p></body></html>"))
